# Generated by Django 3.0.5 on 2020-04-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sensor name')),
                ('i2c_address', models.PositiveIntegerField(blank=True, null=True, verbose_name='I2C address')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
