# Generated by Django 3.1.4 on 2020-12-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm_forecast', '0002_forecast_main_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='city',
            field=models.CharField(help_text='Minsk, Belarus', max_length=20),
        ),
    ]
