# Generated by Django 3.1.7 on 2021-02-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owm_forecast', '0005_auto_20210227_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='latest_data',
            new_name='current_weather_data',
        ),
    ]
