# Generated by Django 3.1.7 on 2021-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm_forecast', '0006_auto_20210227_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='current_air_pollution_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
