# Generated by Django 3.1.7 on 2021-02-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm_forecast', '0007_forecast_current_air_pollution_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='geo_coord',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
