# Generated by Django 3.2 on 2021-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owm_forecast', '0008_forecast_geo_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
