# Generated by Django 3.0.3 on 2020-03-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('lng', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
