# Generated by Django 3.1.4 on 2020-12-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barometer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barometer',
            old_name='pressure_pha',
            new_name='pressure_hpa',
        ),
        migrations.RenameField(
            model_name='barometer',
            old_name='temperature',
            new_name='temperature_c',
        ),
    ]
