# Generated by Django 3.1.4 on 2020-12-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('barometer', '0002_auto_20201206_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='barometer',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.device'),
        ),
    ]
