# Generated by Django 3.1.4 on 2020-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barometer', '0003_barometer_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='barometer',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-06 17:37:23.776197'),
            preserve_default=False,
        ),
    ]
