# Generated by Django 3.1.4 on 2020-12-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barometer', '0004_barometer_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barometer',
            options={'ordering': ('device', 'time_created'), 'verbose_name': 'Barometer', 'verbose_name_plural': 'Barometer'},
        ),
    ]
