# Generated by Django 3.1.4 on 2020-12-19 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barometer', '0007_auto_20201219_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barometer',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
