# Generated by Django 3.1.4 on 2020-12-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barometer', '0008_auto_20201219_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barometer',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
