# Generated by Django 3.2 on 2021-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barometer', '0009_auto_20201219_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barometer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
