# Generated by Django 3.1.4 on 2020-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, 'Barometer')])),
                ('sub_type', models.PositiveSmallIntegerField(choices=[(1, 'BME280')])),
                ('address_type', models.PositiveSmallIntegerField(choices=[(1, 'I2C'), (2, 'Ethernet/WiFi')])),
                ('i2c_address', models.CharField(default='', max_length=5, verbose_name='I2C address')),
                ('ip_address', models.GenericIPAddressField(default='')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
