# Generated by Django 3.1.4 on 2020-12-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201206_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='i2c_address',
            field=models.CharField(blank=True, help_text='e.g. 0x76', max_length=5, null=True, verbose_name='I2C address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='e.g. 192.168.0.17', null=True),
        ),
    ]
