# Generated by Django 3.1.4 on 2020-12-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201206_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('id',), 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
    ]
