# Generated by Django 3.1.6 on 2021-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_device_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I2C'), (2, 'Ethernet/WiFi'), (3, 'Bluetooth')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Barometer'), (2, 'LED Strip')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='sub_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BME280'), (2, 'RGB Strip with alarm')]),
        ),
    ]
