# Generated by Django 3.1.7 on 2021-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210214_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bluetooth_uuid_rx',
            field=models.CharField(blank=True, help_text='e.g. 0000ffe1-0000-1000-8000-00805f9b34fb', max_length=100, null=True, verbose_name='Bluetooth UUID RX'),
        ),
        migrations.AddField(
            model_name='device',
            name='bluetooth_uuid_tx',
            field=models.CharField(blank=True, help_text='e.g. 0000ffe1-0000-1000-8000-00805f9b34fb', max_length=100, null=True, verbose_name='Bluetooth UUID TX'),
        ),
    ]
