class Choices:
    DEVICE_TYPE_BAROMETER = 1
    DEVICE_TYPE_LED_STRIP = 2
    DEVICE_TYPE_CHOICES = [
        (DEVICE_TYPE_BAROMETER, 'Barometer'),
        (DEVICE_TYPE_LED_STRIP, 'LED Strip'),
    ]

    DEVICE_SUB_TYPE_BME280 = 1
    DEVICE_SUB_TYPE_RGB_STRIP_WITH_ALARM = 2
    DEVICE_SUB_TYPE_CHOICES = [
        (DEVICE_SUB_TYPE_BME280, 'BME280'),
        (DEVICE_SUB_TYPE_RGB_STRIP_WITH_ALARM, 'RGB Strip with alarm'),
    ]

    DEVICE_ADDRESS_TYPE_I2C = 1
    DEVICE_ADDRESS_TYPE_ETH_WIFI = 2
    DEVICE_ADDRESS_TYPE_BLUETOOTH = 3
    DEVICE_ADDRESS_TYPE_CHOICES = [
        (DEVICE_ADDRESS_TYPE_I2C, 'I2C'),
        (DEVICE_ADDRESS_TYPE_ETH_WIFI, 'Ethernet/WiFi'),
        (DEVICE_ADDRESS_TYPE_BLUETOOTH, 'Bluetooth'),
    ]

    FORECAST_UNITS_STANDARD = 1
    FORECAST_UNITS_METRIC = 2
    FORECAST_UNITS_IMPERIAL = 3
    FORECAST_UNITS_CHOICES = [
        (FORECAST_UNITS_STANDARD, 'standard'),
        (FORECAST_UNITS_METRIC, 'metric'),
        (FORECAST_UNITS_IMPERIAL, 'imperial'),
    ]
